//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScenarioAccounting
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ClassifierThingCommand
    {
        public int id { get; set; }

        [Display(Name = "Подтип актуатора")]
        public int SubTypeID { get; set; }

        [Display(Name = "Команда")]
        public string Text { get; set; }
    
        public virtual ClassifierSubTypeThing ClassifierSubTypeThing { get; set; }
    }
}
