//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScenarioAccounting
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Actuators = new HashSet<Actuator>();
            this.SensorMNs = new HashSet<SensorMN>();
        }
    
        public int id { get; set; }

        [Display(Name = "Название")]
        public string Name { get; set; }

        [Display(Name = "Этаж")]
        public int Floor { get; set; }

        [Display(Name = "Площадь")]
        public double Area { get; set; }

        [Display(Name = "Дата создания")]
        public System.DateTime CreationDate { get; set; }

        [Display(Name = "Дата окончания эксплуатации")]
        public Nullable<System.DateTime> TerminationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actuator> Actuators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SensorMN> SensorMNs { get; set; }
    }
}
