//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScenarioAccounting
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SensorCondition
    {
        public int id { get; set; }

        [Display(Name = "Сценарий")]
        public int ScenarioID { get; set; }

        [Display(Name = "Датчик")]
        public int SensorID { get; set; }

        [Display(Name = "Знак")]
        public int SignID { get; set; }

        [Display(Name = "Показания датчика")]
        public int Value { get; set; }
    
        public virtual ClassifierSign ClassifierSign { get; set; }
        public virtual Scenario Scenario { get; set; }
        public virtual SensorMN SensorMN { get; set; }
    }
}
