//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScenarioAccounting
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SysUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysUser()
        {
            this.Scenarios = new HashSet<Scenario>();
        }
    
        public int id { get; set; }
        [Display(Name = "Паспорт")]
        public string Passport { get; set; }

        [Display(Name = "Фамилия")]
        public string Surname { get; set; }
        
        [Display(Name = "Имя")]
        public string Name { get; set; }
        
        [Display(Name = "Отчество")]
        public string Patronymic { get; set; }
        
        [Display(Name = "Дата рождения")]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public System.DateTime Birthdate { get; set; }

        [Display(Name = "Пол")]
        public int Sex { get; set; }

        [Display(Name = "Тип пользователя")]
        public int UserType { get; set; }

        [Display(Name = "Логин")]
        public string Login { get; set; }

        [Display(Name = "Пароль")]
        public string Password { get; set; }

        [Display(Name = "Дата окончания работы")]
        [DisplayFormat(DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> TerminationDate { get; set; }

        [Display(Name = "Пол")]
        public virtual ClassifierSex ClassifierSex { get; set; }

        [Display(Name = "Тип пользователя")]
        public virtual ClassifierUserType ClassifierUserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "Автор")]
        public virtual ICollection<Scenario> Scenarios { get; set; }
    }
}
