//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScenarioAccounting
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TimeWeatherCondition
    {
        public int id { get; set; }

        [Display(Name = "Сценарий")]
        public int ScenarioID { get; set; }

        [Display(Name = "Значение")]
        public int ValueID { get; set; }
    
        public virtual ClassifierTimeWeather ClassifierTimeWeather { get; set; }
        public virtual Scenario Scenario { get; set; }
    }
}
